format = """
$username\
$directory\
$git_branch\
$git_status\
$fill\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$conda\
$python\
$time\n  \
[󱞪](fg:purple) \
"""

palette = "dracula"

[palettes.dracula]
background = '#282a36'
current_line = '#44475a'
foreground = '#f8f8f2'
comment = '#6272a4'
cyan = '#8be9fd'
green = '#50fa7b'
orange = '#ffb86c'
pink = '#ff79c6'
purple = '#bd93f9'
red = '#ff5555'
yellow = '#f1fa8c'

[directory]
format = "[](fg:current_line)[ $path ]($style)[](fg:current_line) "
style = "bg:current_line fg:cyan"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
Documents = "󰈙"
Downloads = " "
Music = " "
Pictures = " "

[fill]
style = "fg:current_line"
symbol = " "

[git_branch]
format = "[](fg:current_line)[ $symbol $branch ]($style)[](fg:current_line) "
style = "bg:current_line fg:purple"
symbol = ""

[git_status]
disabled = false
style = "bg:current_line fg:red"
format = '[](fg:current_line)([$all_status$ahead_behind]($style))[](fg:current_line) '
up_to_date = '[ ✓ ](bg:current_line fg:green)'
untracked = '[?\($count\)](bg:current_line fg:orange)'
stashed = '[\$](bg:current_line fg:purple)'
modified = '[!\($count\)](bg:current_line fg:orange)'
renamed = '[»\($count\)](bg:current_line fg:purple)'
deleted = '[✘\($count\)](style)'
staged = '[++\($count\)](bg:current_line fg:green)'
ahead = '[⇡\(${count}\)](bg:current_line fg:cyan)'
diverged = '⇕[\[](bg:current_line fg:purple)[⇡\(${ahead_count}\)](bg:current_line fg:cyan)[⇣\(${behind_count}\)](bg:current_line fg:pink)[\]](bg:current_line fg:purple)'
behind = '[⇣\(${count}\)](bg:current_line fg:pink)'

[time]
disabled = false
format = " [](fg:current_line)[ $time 󰴈 ]($style)[](fg:current_line)"
style = "bg:current_line fg:yellow"
time_format = "%I:%M%P"
use_12hr = true

[username]
disabled = false
format = "[](fg:current_line)[ 󰧱 $user ]($style)[](fg:current_line) "
show_always = true
style_root = "bg:current_line fg:red"
style_user = "bg:current_line fg:purple"

# Languages

[c]
style = "bg:current_line fg:cyan"
format = " [](fg:current_line)[ $symbol$version ]($style)[](fg:current_line)"
disabled = false
symbol = " "

[elixir]
style = "bg:current_line fg:purple"
format = " [](fg:current_line)[ $symbol$version ]($style)[](fg:current_line)"
disabled = false
symbol = " "

[elm]
style = "bg:current_line fg:cyan"
format = " [](fg:current_line)[ $symbol$version ]($style)[](fg:current_line)"
disabled = false
symbol = " "

[golang]
style = "bg:current_line fg:cyan"
format = " [](fg:current_line)[ $symbol$version ]($style)[](fg:current_line)"
disabled = false
symbol = " "

[haskell]
style = "bg:current_line fg:purple"
format = " [](fg:current_line)[ $symbol$version ]($style)[](fg:current_line)"
disabled = false
symbol = " "

[java]
style = "bg:current_line fg:orange"
format = " [](fg:current_line)[ $symbol$version ]($style)[](fg:current_line)"
disabled = false
symbol = " "

[julia]
style = "bg:current_line fg:pink"
format = " [](fg:current_line)[ $symbol$version ]($style)[](fg:current_line)"
disabled = false
symbol = " "

[nodejs]
style = "bg:current_line fg:green"
format = " [](fg:current_line)[ $symbol$version ]($style)[](fg:current_line)"
disabled = false
symbol = "󰎙 "

[nim]
style = "bg:current_line fg:yellow"
format = " [](fg:current_line)[ $symbol$version ]($style)[](fg:current_line)"
disabled = false
symbol = "󰆥 "

[rust]
style = "bg:current_line fg:orange"
format = " [](fg:current_line)[ $symbol$version ]($style)[](fg:current_line)"
disabled = false
symbol = " "

[scala]
style = "bg:current_line fg:red"
format = " [](fg:current_line)[ $symbol$version ]($style)[](fg:current_line)"
disabled = false
symbol = " "

[python]
style = "bg:current_line fg:green"
format = " [](fg:current_line)[ $symbol$version ]($style)[](fg:current_line)"
disabled = false
symbol = ' '

[conda]
style = "bg:current_line fg:green"
format = " [](fg:current_line)[ $symbol$environment ]($style)[](fg:current_line)"
disabled = false
symbol = '🅒 '
